### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by KiwoonHong** [INFO526-DataViz/project-final-Visual-Virtuosos#1]
The following is the peer review of the project proposal by [Chart Champions]. The team members that participated in this review are 

- [Visalakshi Iyer] - @visalakshi2001
- [Megan Hokama] - @meganhokama
- [Sai Madhuri Kandula] - @ksmadhuri
- [Kiwoon Hong] - @KiwoonHong
- [Tejashwini Kasa] - @TejashwiniKasa

- Describe the goal of the project.
The goal of the project is to visualize the population of African Savannah elephants and their ivory trade. The African Savannah elephant, faces an existential crisis due to poaching, habitat loss, and ivory trade. A project aims to study their population trends and ivory trade dynamics from 1995 to 2023, thereby striving to get a better understanding of dynamics between human activities, conservation efforts, and the nature.

- Describe the data used or collected.
African Savannah Elephant Population Data:
The population data for African savannah elephants is sourced from the research paper titled "Continent-wide Survey: Massive Decline in African Savannah Elephants."The dataset contains 322 rows and 7 columns.
Columns:
Country: The name of the country.
Ecosystem: The name of the ecosystem used in the manuscript and supplemental material.
Stratum: Indicates the stratum or ecosystem that was the study area for historical data.
Year: The year of the survey.
Estimate: The estimated number of elephants present.
SE: Standard error, where 0 values indicate total counts and blank indicates missing values for sample counts.
Ivory Trade Data:

The ivory trade data is obtained from the Elephant Trade Information System (ETIS).The dataset contains 88 rows and 12 columns.
Columns:
Country: The name of the country.
Year: The years spanned from 2008 to 2019.
Total: The total number of seizure cases related to the ivory trade.

The African savannah elephant population data provides valuable insights into the population trends and distribution patterns of these elephants over a two-decade period. This data is essential for understanding the challenges faced by the species due to factors like poaching and habitat loss.

The ivory trade data offers information about the illegal trade in ivory, including the number of seizure cases in different countries over a twelve-year period. Analyzing this data can help us understand on the extent of the illegal ivory trade and its impact on elephant populations.

Both datasets are important for the project, allowing you to visualize and analyze the relationships between elephant populations, illegal ivory trade, and other factors affecting the survival of African savannah elephants in the wild.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
In order to answer the 1st question, the team aims to look at the data set to determine how the elephant population varies across different African countries. Their approach includes using regression techniques to identify trends and create a 3-D map plot to visualize elephant populations according to region and country. 
Ultimately, they aim to develop a shiny app that will include interactive elements including the ability to select years, as well as incorporating chloropleths. For Q2, the team aims to analyze the ivory trade in Africa and identify any trends. A time series plot will showcase the trends of the ivory trade in Africa.

- Is there anything that is unclear from the proposal?
- What will be the validation set for the estimation model that determines the quality of the fit? It is unclear from the proposal as how will the team know that the predictions are accurate.
- What is the basis of choosing the mentioned models, as the `dataset.xlsx` shows categorical independent variables and a numeric target variable. 
- How are the prediction of estimates utilized in the final output? Are they visualizing the past and predictions together or separately?
- How will the analysis of ivory trade trends in Q2 present impact on the elephant population? How are they stitching both the concepts together?
- Based on which metrics will the models be evaluated?

- Provide constructive feedback on how the team might be able to improve their project.
- While the proposal is very well written, there is very little information on how the output of the model will be utilized in the final part of the project. It would be helpful to include where the predictions go on the visualization.
- The team can try and incorporate boosting or bagging models rather than regularization models like lasso. This suggestion comes from the fact that the data has a lot of unique values in each independent variables, as well as most of them are of type `object`.
- It will be helpful if the one-liner goal of the project is mentioned in the start of the proposal. This is required as per the point system.
- We suggest that the metrics of model evaluation as well as the source of validating the predictions (testing/validation set source) be mentioned in the proposal. For this the team might need to gather data in the respective years of 2015-2023 or 2020-2023 or mention that there is no validation set and that they are splitting the complete dataset intro train/test/validation.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The aspect of the project that we are most interested is using the different regression models to predict the population of elephants for 7 years and not just 1 year and we want to see how the 3D map plot turns out to be. We are also excited to see the relationship between the elephant population and ivory trade in the African countries.

- Provide constructive feedback on any issues with file and/or code organization.
1. There is a folder called `presentation_files/` that belongs to the `freeze_/` folder. Try and exclude it from the main repository
2. There is also ReadMe.html that doesn't belong in the main working directory. Same for `README_files/libs`
3. Rest of the repository looks good and you have done a great work including the data files to their respective spaces.

- (Optional) Any further comments or feedback?
Best wishes from team Chart Champions

**Comment by partha-pkp** [comment]
Hi Team,

At this initial stage, our focus was primarily on providing a comprehensive overview of the project scope and outlining a feasible weekly action plan for the next seven weeks.

As we progress through the project, we anticipate gaining more insights and refining our approach based on evolving requirements and emerging challenges.

We appreciate your understanding and thanks for the feedback!
