### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Shakir0585** [INFO526-DataViz/project-final-Visual-Virtuosos#2]
The following is the peer review of the project proposal by Data Dynamos. The team members that participated in this review are 

- Ansh Kumar Dev - @Anshkumardev
- Rahul Bangad - @rahulbangad98
- Swati Das - @Swati09Das
- Deema Albluwi - @deec0dez
- Shakir Ahmed - @Shakir0585

- Describe the goal of the project.
The main objective of the project is to make a map and understanding the number of African savannah elephant population over time and also to depict the illegal ivory trade.

- Describe the data used or collected.
Two main types of information are being used:
Number of elephants from 1995 to 2014, which includes details like the country, the type of place they live, and the population of elephants. 
Records of illegal ivory trading from 2008 to 2019, showing which countries are involved and how many times ivory was seized.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Ensure that the datasets are clean and accurate.
Perform exploratory data analysis to identify any trends or patterns.
Use different types of math models to predict the number of elephants and ivory trades from 2015 to 2023 based on historic data.
Select the math prediction model that works the best for the dataset.
Display the result in the form of an interactive map, which shows the population for each country.

- Is there anything that is unclear from the proposal?
The plan does not discuss the method used to choose the best math model or what steps they'll take if the output is not as expected. It is also unclear as to how and which predictor variables / attributes will be used to predict the number, considering the factors affecting elephant population is not present.

- Provide constructive feedback on how the team might be able to improve their project.
        - Have a backup plan in case things don't go as expected with the data, considering there are less prediction attributes / classes.
        - Consider the rules and regulations around sharing data about elephants.
        - Test the map visualization to make sure there are no unforeseen bugs while rendering in GitHub, and also perform a 'within team peer review' in a new file to make sure there are no dependencies or deviations from proposed plan.
        - Ensure that the map visualization is easily accessible and easy to understand maneuver.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The concept of predicting of elephants based on historical data is very intriguing. Visualizing it in the form of a graph is also very interesting, and we are looking forward to the completed project and understanding in depth as to how they went about this task.

- Provide constructive feedback on any issues with file and/or code organization.
The folders in the project are well named and organization structure is added with all folder's purpose highlighted. 

- (Optional) Any further comments or feedback?
This project could really help save elephants. Working with animal protection groups could make it even better. Maybe they can also use satellite pictures or animal tracking data to learn more. It's important that everyone can understand their findings, not just scientists. All the very best!!!

**Comment by KashyapNadendla** [comment]
Hi Team,

Thank you for the review, we have taken your feedback in consideration and made changes where required.
