### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-final-Visual-Virtuosos#3]
Dear Visual Virtuosos: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |        2.5 |
| Proposal | 5         |       4.5 |
| Workflow | 1         |      1  |
| Teamwork | 1         |      1  |
| Total    | 10        |       9 |

**Feedback**: 
Data: remember that it's important to show the data types as well. 
Proposal: I don't agree with some of the peer review on the need to have all of the regression steps figured out now, but it would be relevant to include what you will be examining to determine which model to use. I also think you should have a few concrete objectives or outcome identified in bullets.  
Overall: the project is interesting and relevant.

**Comment by Jothish21** [comment]
Hi Dr. Gregg,

We have added the data types and stated our main objectives to achieve in bullets from this project. Thank you very much for the proposal evaluation 😊.
