### ISSUE TITLE
Project proposal regrade

### ISSUE THREAD

**Issue by KashyapNadendla** [INFO526-DataViz/project-final-Visual-Virtuosos#4]
Hi Dr. Greg,

The Visual Virtuosos team request you for a regrade of the project proposal.

Data type has been added to the dataset description and we have stated our objective in bullet points . Thank you for your feedback!

**Comment by Gchism94** [comment]
Good work. I gave you full credit on the regrade. The final score for the proposal is 9.5/10 (the mid-point between 9 and 10)

**Comment by KashyapNadendla** [comment]
Hi Dr. Greg,

Thank you for the regrade.
