### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by visalakshi2001** [INFO526-DataViz/project-final-Visual-Virtuosos#5]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

- [Visalakshi Iyer] - @visalakshi2001

- [Megan Hokama] - @meganhokama

- [Sai Madhuri Kandula] - @ksmadhuri

- [Kiwoon Hong] - @KiwoonHong

- [Tejashwini Kasa] - @TejashwiniKasa
---

#### 1. Purpose of Code
- [x] Clearly defined and understood
- [ ] Ambiguous or unclear

---

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [x] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [x] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [x] Code documentation (e.g., comments) is sufficient
- [x] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [x] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ ] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.
The libraries are imported twice, once using `pacman and then lines [102-104] have repeated imports of some packages.
---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [x] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by KashyapNadendla** [comment]
Hi Team,

Thank you for your feedback.

- Virtual Virtuosos
