### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by visalakshi2001** [INFO526-DataViz/project-final-Visual-Virtuosos#7]
The following is the peer review of the Presentation proposal by Chart Champions. The team members that participated in this review are 

- Visalakshi Iyer - @visalakshi2001

- Tejaswini Kasa - @TejashwiniKasa

- Sai Madhuri Kandula - @ksmadhuri

- Megan Hokama - @meganhokama

- Kiwoon Hong - @KiwoonHong

- Content: Is the research question well designed and is the data being used relevant to the research question?
> Yes, the research question is well-designed, and the data is relevant to the question. Limitations of the project were not considered explicitly in the presentation. However, the group did acknowledge there were some struggles during the question portion. It seems like overall they took considerate planning and implementation for the project. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
> Yes, the visualizations were accurately interpreted. The slides are well organized and the text is readable. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
> Yes, critical thought was put into the project, and limitations were accurately handled. It is evident that much effort is put into the project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
> Yes slides are well organized and easy to read, the transition between the plots and the app could have been refined. Overall, the delivery was great, and the teamwork in delivering the insights made it perfect.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
> Yes, mostly they presented perfectly. there was an understanding between the team members, as well as good tuning. Everyone explained their points nicely. The team members seemed to be well-practiced and didn't read off of a script. They also equally split up their parts so each team member spoke.

**Comment by partha-pkp** [comment]
Hi Team,

Thank you for the feedback!
