### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by d-koudz** [INFO526-DataViz/project-final-Visual-Virtuosos#8]
The following is the peer review of the presentation proposal by Data Dynamos. The team members who participated in this review are:

- Ansh Kumar Dev - @Anshkumardev

- Rahul Bangad - @rahulbangad98

- Swati Das - @Swati09Das

- Deema Albluwi - @Deec0dez

- Shakir Ahmed - @Shakir0585

- Describe the goal of the project.

The project aims to investigate the decline in African savannah elephants, using a comprehensive data-driven approach. This includes examining the trends in elephant populations over the years and analyzing the ivory trade in Africa.

- Content: Is the research question well designed and is the data being used relevant to the research question?

The research question appears to be well-designed, focusing on the trend of elephant populations and ivory trade in Africa. 
The data used, including a continent-wide survey on African savannah elephants and CITES (Convention on International Trade in Endangered Species of Wild Fauna and Flora) data on ivory trade, is highly relevant to the research question.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

The team used various visualizations like 3D plots, line graphs, bar plots, and maps, which seemed appropriate for the data presented.
The interpretations, such as the population trend analysis and the prediction models, are aligned with the data visualizations and are accurately interpreted based on the provided content.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The project reflects careful thought and creativity, particularly in the use of diverse data sources and advanced analytical methods, which indicates a deep engagement with the subject.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides are well-organized, with clear headings and structured content.
The use of figures, minimal text, and interactive elements like Plotly graphs suggests a high level of readability and engagement.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The team showed a high level of professionalism while presenting.
The presentation was well-prepared and well-practiced, and all team members contributed equally.

P.S. Your plots were impressive. Great work!

**Comment by partha-pkp** [comment]
Hi Team,

Thank you for the feedback!
